"""Doubao-style prompt builder.

This style is Chinese-only and asks the LLM for a simpler JSON output where
each round is labelled either ``normal`` or ``interruption``. The control
tokens ``[S.S] / [C.S] / [S.L]`` are NOT generated by the LLM here; they are
inserted in the post-processing step ``scripts/05_add_tokens.py``.

Use this style when:

- You only need Chinese data.
- You want to delegate the precise truncation of the assistant turn and the
  random fake-vs-real interruption split to the deterministic post-processing
  (it gives you tighter control over interruption ratios).
"""

import random
from typing import Optional

from ..topics import ZH_TOPICS
from ..scenarios import ZH_SCENARIOS
from ..speaking_styles import select_style


def build_prompt(rng: Optional[random.Random] = None) -> str:
    """Build a single Chinese prompt for the Doubao-style data flow."""
    rng = rng or random

    num_rounds = rng.choice([2, 3, 4, 5, 6, 7, 8])
    interrupt_times = rng.randint(1, num_rounds - 1)
    interruption_rounds = sorted(rng.sample(range(1, num_rounds), interrupt_times))

    if len(interruption_rounds) > 1 and 1 in interruption_rounds:
        # Avoid interrupting on the very first round in multi-interrupt setups.
        interruption_rounds.remove(1)
        interrupt_times -= 1
    if len(interruption_rounds) == 1 and 1 in interruption_rounds:
        interruption_rounds.remove(1)
        interruption_rounds.append(num_rounds)

    topic = rng.choice(ZH_TOPICS)
    style = select_style("zh", rng)

    prompt = (
        "任务：生成一段用户（user）和 AI 语音助手（assistant）之间的问答对话记录。"
        "每一轮问答包括用户的一次提问和及助手的一次回复。"
    )
    prompt += (
        f"请生成{num_rounds}轮对话。"
        f"用户从一个与'{topic}'相关的话题开始对话，"
    )
    prompt += (
        f"用户的说话风格是{style}的。并在第{interruption_rounds}轮中打断助手。"
        f"助手可以使用填充词或者口语化的表达，回复尽量充分，并根据上下文问答的内容回复，以营造随意、友好的氛围。 "
    )

    seen_scenario = []
    for i in range(interrupt_times):
        scenario_i = rng.choice(ZH_SCENARIOS)
        prompt += (
            f"在第{interruption_rounds[i]}轮中，用户在系统回复后打断系统，"
            f"打断形式为'{scenario_i['name']}'。"
        )
        if scenario_i not in seen_scenario:
            prompt += f"在这种情况下， {scenario_i['description']}例如: {scenario_i['example']}"
            seen_scenario.append(scenario_i)

    prompt += (
        f"其他轮次为正常对话。"
        f"对话输出为JSON格式：包含{num_rounds}个top-level keys，例如 \\\"Round 1\\\", "
        f"\\\"Round 2\\\"等。每一轮对话中包含如下内容："
    )
    prompt += (
        "{\\\"type\\\": 对话类型 (如 \\\"normal\\\" 或  \\\"interruption\\\")， "
        "\\\"user\\\": 用户提问, \\\"assistant\\\": 系统回复}。"
    )
    return prompt
